### ISSUE TITLE
ToDo list for v0.1.0

### ISSUE THREAD

**Issue by trappitsch** [galactic-forensics/RPyScope#1]
The first batch is done, but it would be good to get some more things in before giving the thing a version number. Here are some milestones for v0.1.0:

- [x] Testing of the microscope and cameras
- [x] Menu for Settings, Exit, etc.
- [x] Settings panel that is re-applied on startup
  - [x] Rotation of image
  - [x] Mirroring
  - [x] Remember path
  - [x] Set image and video format
- [x] Framerate and resolution control (hand in hand)
- [x] Possibility to operate the whole app without mouse
- [ ] Fix crashes while recording video

**Comment by trappitsch** [comment]
@lindlou: This was my todo list for `v0.1.0` from quite some time ago. Have a look at what you think / check off tasks that you have finished. We can discuss other improvements and extend the to do list here :)

**Comment by lindlou** [comment]
`Use init script toggle`: what does that mean?
`Move path to save images to to settings`: In our case it is more practical to have it in the main window, because for every user and every experiment we use a different path, so we modify it almost every time we use the app.
`init.py`: What is it?

**Comment by trappitsch** [comment]
> `Use init script toggle`: what does that mean?

This is connected to the last, but I think is obsolete by now.

> `Move path to save images to to settings`: In our case it is more practical to have it in the main window, because for every user and every experiment we use a different path, so we modify it almost every time we use the app.

Sounds good. Might still be good though to save the path whenever a photo is taken in a hidden setting, just so in case the software gets restarted, the user is still in the same folder. But I agree, this can be a hidden setting that is only indirectly set.

> `init.py`: What is it?

User initialization script, instead of settings. Kind of obsolete by now.

**Comment by lindlou** [comment]
Is it ok if I modify the todo list (already did it once) or should I post a second one?

**Comment by trappitsch** [comment]
no go ahead and modify it. i tossed a few things already :)

**Comment by lindlou** [comment]
About the path: I already implemented a setting called `default_directory`, which is the path set at startup (in our case, `~/Desktop`). Do you think it would be better to remove this setting and remember the previous path instead (for instance `~/Desktop/Louis` or `~Desktop/Alison`?
